name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "4,11,28,37,52 9-11,13-16 1-5,8-17,19-23,27-30 * 1-5"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "3262153358@qq.com"
          git config --local user.name "Chino Arror"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
